using System;
using System.IO;
using FlickSort.UI;
using TMPro;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.UI;

namespace FlickSort.Editor
{
    [InitializeOnLoad]
    public static class FlickSortVisualSetup
    {
        private const string Root = "Assets/Game";
        private const string MaterialsFolder = Root + "/3D/Materials";
        private const string TrailMaterialsFolder = Root + "/VFX/FlickSort/Materials";
        private const string UiPrefabFolder = Root + "/Prefabs/UI";
        private const string VfxPrefabFolder = Root + "/Prefabs/VFX";
        private const string ChipPrefabPath = Root + "/Prefabs/Gameplay/Chip.prefab";
        private const string MarkerPath = Root + "/.visual-setup-v1";

        static FlickSortVisualSetup()
        {
            EditorApplication.delayCall += RunOnce;
        }

        [MenuItem("Flick Sort/Build Visual Assets")]
        public static void BuildVisualAssets()
        {
            EnsureFolder(MaterialsFolder);
            EnsureFolder(TrailMaterialsFolder);
            EnsureFolder(UiPrefabFolder);
            EnsureFolder(VfxPrefabFolder);

            var red = CreateLitMaterial("Chip_Red", new Color(0.90f, 0.12f, 0.14f));
            CreateLitMaterial("Chip_Blue", new Color(0.10f, 0.42f, 0.95f));
            CreateLitMaterial("Chip_Yellow", new Color(1.00f, 0.72f, 0.08f));
            CreateLitMaterial("Chip_Purple", new Color(0.58f, 0.18f, 0.88f));
            CreateLitMaterial("Chip_Green", new Color(0.10f, 0.72f, 0.36f));

            var trailMaterial = CreateTrailMaterial();
            var circle = LoadSprite(Root + "/UI/KenneyUIPack/PNG/Blue/Default/icon_circle.png");
            var buttonSprite = LoadSprite(Root + "/UI/KenneyUIPack/PNG/Blue/Default/button_rectangle_depth_flat.png");
            var blobShadow = CreateBlobShadow(circle);

            CreateWinPopup(buttonSprite);
            UpgradeChipPrefab(blobShadow, trailMaterial);

            File.WriteAllText(MarkerPath, "Generated by Flick Sort/Build Visual Assets.\n");
            AssetDatabase.ImportAsset(MarkerPath);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"Flick Sort visual setup complete. Default chip palette starts with {red.name}.");
        }

        private static void RunOnce()
        {
            if (Application.isBatchMode || File.Exists(MarkerPath))
                return;

            BuildVisualAssets();
        }

        private static Material CreateLitMaterial(string name, Color color)
        {
            var path = $"{MaterialsFolder}/{name}.mat";
            var shader = Shader.Find("Universal Render Pipeline/Lit");
            if (shader == null)
                throw new InvalidOperationException("URP Lit shader was not found.");

            var material = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (material == null)
            {
                material = new Material(shader) { name = name };
                AssetDatabase.CreateAsset(material, path);
            }

            material.shader = shader;
            material.SetColor("_BaseColor", color);
            material.SetFloat("_Metallic", 0.08f);
            material.SetFloat("_Smoothness", 0.62f);
            material.enableInstancing = true;
            EditorUtility.SetDirty(material);
            return material;
        }

        private static Material CreateTrailMaterial()
        {
            const string path = TrailMaterialsFolder + "/Trail_Additive.mat";
            var shader = Shader.Find("Universal Render Pipeline/Particles/Unlit");
            if (shader == null)
                throw new InvalidOperationException("URP Particles/Unlit shader was not found.");

            var material = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (material == null)
            {
                material = new Material(shader) { name = "Trail_Additive" };
                AssetDatabase.CreateAsset(material, path);
            }

            material.shader = shader;
            material.SetColor("_BaseColor", new Color(0.65f, 0.88f, 1f, 0.45f));
            material.SetFloat("_Surface", 1f);
            material.SetFloat("_Blend", 2f);
            material.SetFloat("_SrcBlend", (float)BlendMode.SrcAlpha);
            material.SetFloat("_DstBlend", (float)BlendMode.One);
            material.SetFloat("_ZWrite", 0f);
            material.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");
            material.renderQueue = (int)RenderQueue.Transparent;
            material.enableInstancing = true;
            EditorUtility.SetDirty(material);
            return material;
        }

        private static GameObject CreateBlobShadow(Sprite circle)
        {
            const string path = VfxPrefabFolder + "/BlobShadow.prefab";
            var root = new GameObject("BlobShadow");
            var renderer = root.AddComponent<SpriteRenderer>();
            renderer.sprite = circle;
            renderer.color = new Color(0f, 0f, 0f, 0.25f);
            renderer.shadowCastingMode = ShadowCastingMode.Off;
            renderer.receiveShadows = false;
            renderer.sortingOrder = -10;
            root.transform.localRotation = Quaternion.Euler(90f, 0f, 0f);
            root.transform.localScale = new Vector3(1.05f, 0.62f, 1f);
            var prefab = PrefabUtility.SaveAsPrefabAsset(root, path);
            UnityEngine.Object.DestroyImmediate(root);
            return prefab;
        }

        private static void UpgradeChipPrefab(GameObject blobShadowPrefab, Material trailMaterial)
        {
            var root = PrefabUtility.LoadPrefabContents(ChipPrefabPath);
            try
            {
                var oldShadow = root.transform.Find("BlobShadow");
                if (oldShadow != null)
                    UnityEngine.Object.DestroyImmediate(oldShadow.gameObject);

                var shadow = (GameObject)PrefabUtility.InstantiatePrefab(blobShadowPrefab);
                shadow.name = "BlobShadow";
                shadow.transform.SetParent(root.transform, false);
                shadow.transform.localPosition = new Vector3(0f, -0.0016f, 0f);
                shadow.transform.localScale = new Vector3(0.0205f, 0.0125f, 0.0205f);

                var trailTransform = root.transform.Find("FlickTrail");
                var trailObject = trailTransform != null ? trailTransform.gameObject : new GameObject("FlickTrail");
                trailObject.transform.SetParent(root.transform, false);
                trailObject.transform.localPosition = Vector3.zero;
                trailObject.transform.localScale = Vector3.one / root.transform.localScale.x;

                var trail = trailObject.GetComponent<TrailRenderer>();
                if (trail == null)
                    trail = trailObject.AddComponent<TrailRenderer>();
                trail.time = 0.14f;
                trail.minVertexDistance = 0.025f;
                trail.widthMultiplier = 0.13f;
                trail.widthCurve = AnimationCurve.EaseInOut(0f, 0.85f, 1f, 0f);
                trail.colorGradient = CreateTrailGradient();
                trail.material = trailMaterial;
                trail.alignment = LineAlignment.View;
                trail.textureMode = LineTextureMode.Stretch;
                trail.emitting = true;
                trail.shadowCastingMode = ShadowCastingMode.Off;
                trail.receiveShadows = false;

                PrefabUtility.SaveAsPrefabAsset(root, ChipPrefabPath);
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }

        private static Gradient CreateTrailGradient()
        {
            var gradient = new Gradient();
            gradient.SetKeys(
                new[]
                {
                    new GradientColorKey(new Color(0.72f, 0.92f, 1f), 0f),
                    new GradientColorKey(new Color(0.24f, 0.66f, 1f), 1f)
                },
                new[]
                {
                    new GradientAlphaKey(0.48f, 0f),
                    new GradientAlphaKey(0f, 1f)
                });
            return gradient;
        }

        private static void CreateWinPopup(Sprite buttonSprite)
        {
            const string path = UiPrefabFolder + "/WinPopup.prefab";
            var root = CreateUiObject("WinPopup", null);
            Stretch(root.GetComponent<RectTransform>());
            var canvasGroup = root.AddComponent<CanvasGroup>();
            var view = root.AddComponent<WinPopupView>();

            var blocker = CreateUiObject("ScreenDim", root.transform);
            Stretch(blocker.GetComponent<RectTransform>());
            blocker.AddComponent<Image>().color = new Color(0.035f, 0.045f, 0.07f, 0.72f);

            var panel = CreateUiObject("Card", root.transform);
            var panelRect = panel.GetComponent<RectTransform>();
            panelRect.anchorMin = panelRect.anchorMax = new Vector2(0.5f, 0.5f);
            panelRect.sizeDelta = new Vector2(760f, 620f);
            panelRect.anchoredPosition = Vector2.zero;
            panel.AddComponent<Image>().color = new Color(0.98f, 0.96f, 0.90f, 1f);

            var title = CreateText("Title", panel.transform, "SORTED!", 92, new Color(0.10f, 0.13f, 0.20f));
            SetRect(title.rectTransform, new Vector2(0.5f, 0.72f), new Vector2(650f, 130f));

            var subtitle = CreateText("Subtitle", panel.transform, "LEVEL COMPLETE", 42, new Color(0.25f, 0.30f, 0.40f));
            SetRect(subtitle.rectTransform, new Vector2(0.5f, 0.52f), new Vector2(650f, 90f));

            var buttonObject = CreateUiObject("NextButton", panel.transform);
            var buttonRect = buttonObject.GetComponent<RectTransform>();
            SetRect(buttonRect, new Vector2(0.5f, 0.23f), new Vector2(460f, 145f));
            var buttonImage = buttonObject.AddComponent<Image>();
            buttonImage.sprite = buttonSprite;
            buttonImage.type = Image.Type.Sliced;
            var button = buttonObject.AddComponent<Button>();
            button.targetGraphic = buttonImage;
            var colors = button.colors;
            colors.highlightedColor = new Color(1f, 1f, 1f, 1f);
            colors.pressedColor = new Color(0.78f, 0.88f, 1f, 1f);
            button.colors = colors;

            var buttonText = CreateText("Label", buttonObject.transform, "NEXT", 46, Color.white);
            Stretch(buttonText.rectTransform);

            var serializedView = new SerializedObject(view);
            serializedView.FindProperty("canvasGroup").objectReferenceValue = canvasGroup;
            serializedView.FindProperty("nextButton").objectReferenceValue = button;
            serializedView.ApplyModifiedPropertiesWithoutUndo();

            PrefabUtility.SaveAsPrefabAsset(root, path);
            UnityEngine.Object.DestroyImmediate(root);
        }

        private static Sprite LoadSprite(string path)
        {
            var importer = AssetImporter.GetAtPath(path) as TextureImporter;
            if (importer == null)
                throw new FileNotFoundException($"Required Kenney sprite not found: {path}");

            if (importer.textureType != TextureImporterType.Sprite || importer.mipmapEnabled)
            {
                importer.textureType = TextureImporterType.Sprite;
                importer.spriteImportMode = SpriteImportMode.Single;
                importer.mipmapEnabled = false;
                importer.alphaIsTransparency = true;
                importer.SaveAndReimport();
            }

            return AssetDatabase.LoadAssetAtPath<Sprite>(path);
        }

        private static TextMeshProUGUI CreateText(
            string name,
            Transform parent,
            string value,
            int size,
            Color color)
        {
            var obj = CreateUiObject(name, parent);
            var text = obj.AddComponent<TextMeshProUGUI>();
            text.text = value;
            text.font = AssetDatabase.LoadAssetAtPath<TMP_FontAsset>(
                Root + "/Sprite/KenneyUIPack/Font/Kenney Future SDF.asset");
            text.fontSize = size;
            text.color = color;
            text.alignment = TextAlignmentOptions.Center;
            text.enableAutoSizing = true;
            text.fontSizeMin = 18;
            text.fontSizeMax = size;
            text.raycastTarget = false;
            return text;
        }

        private static GameObject CreateUiObject(string name, Transform parent)
        {
            var obj = new GameObject(name, typeof(RectTransform));
            if (parent != null)
                obj.transform.SetParent(parent, false);
            return obj;
        }

        private static void SetRect(RectTransform rect, Vector2 anchor, Vector2 size)
        {
            rect.anchorMin = rect.anchorMax = anchor;
            rect.pivot = new Vector2(0.5f, 0.5f);
            rect.anchoredPosition = Vector2.zero;
            rect.sizeDelta = size;
        }

        private static void Stretch(RectTransform rect)
        {
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.offsetMin = Vector2.zero;
            rect.offsetMax = Vector2.zero;
        }

        private static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path))
                return;

            var parent = Path.GetDirectoryName(path)?.Replace('\\', '/');
            var name = Path.GetFileName(path);
            if (!string.IsNullOrEmpty(parent) && !AssetDatabase.IsValidFolder(parent))
                EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, name);
        }
    }
}
